service: my-serverless-app

plugins:
  - serverless-sequelize-migrations
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    DB_DIALECT: ${env:DB_DIALECT}
    DB_NAME: ${env:DB_NAME}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}

custom:
  migrationsPath: './src/custom/migrations'
  seedersPath: './src/custom/seeders'
